version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: sprout-gis-postgres
    environment:
      POSTGRES_DB: sprout_gis
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # 개발용 pgAdmin (선택사항)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sprout-gis-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN:-admin@sprout.com}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PW:-admin123!}
    ports:
      - "9999:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: