version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: strout-gis-postgres
    environment:
      POSTGRES_DB: strout_gis
      POSTGRES_USER: strout
      POSTGRES_PASSWORD: strout123!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # 개발용 pgAdmin (선택사항)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: strout-gis-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@strout.com
      PGADMIN_DEFAULT_PASSWORD: admin123!
    ports:
      - "9999:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: