version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: sprout-gis-postgres
    environment:
      POSTGRES_DB: sprout_gis
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # 개발용 pgAdmin (선택사항)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sprout-gis-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN:-admin@sprout.com}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PW:-admin123!}
    ports:
      - "9999:80"
    depends_on:
      - postgres
    restart: unless-stopped

  # Prometheus - 메트릭 수집
  prometheus:
    image: prom/prometheus:latest
    container_name: sprout-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped

  # Grafana - 대시보드
  grafana:
    image: grafana/grafana:latest
    container_name: sprout-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123!}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprout-spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/sprout_gis
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
    restart: no
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.8'      # 최소 80% 보장
          memory: 400M     # 최소 400MB

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: