# 운영환경 - Actuator 최소한만
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: false

logging:
  level:
    org.springframework.web: WARN
    org.hibernate: WARN