spring:
  profiles:
    active: default
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/config/web.yml
      - classpath:/config/db.yml
      - classpath:/config/gis.yml

logging:
  level:
    com.strout.api: DEBUG