spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

logging:
  level:
    com.strout.api: DEBUG
  pattern:
    console: '%d{HH:mm:ss} %-5level %logger{36} - %msg%n'