spring:
  profiles:
    active: default
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/config/web.yml
      - classpath:/config/db.yml
      - classpath:/config/gis.yml
      - classpath:/config/monitoring.yml
      - classpath:/config/aws.yml
      - classpath:/config/swagger.yml
      - classpath:/config/ai.yml
      - classpath:/config/notification.yml

server:
  tomcat:
    threads:
      max: 15
      min-spare: 3
    accept-count: 50
    connection-timeout: 20000

logging:
  level:
    com.sprout.api: INFO